NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
#import library
import numpy as np

In [11]:
#1D array
lst=[1,2,3,4]
arr=np.array(lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [13]:
#2D array
import numpy as np
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])

In [7]:
arr1.shape

(3, 5)

In [8]:
arr

array([1, 2, 3, 4])

In [14]:
#indexing
arr[3]

4

In [15]:
arr[3]=5

In [16]:
arr

array([1, 2, 3, 5])

In [17]:
#shows last elemnt
arr[-1]

5

In [18]:
#prints except last element
arr[:-1]

array([1, 2, 3])

In [19]:
#will skip 3 elements
arr[::-3]

array([5, 1])

In [20]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [21]:
arr1[:,1]

array([2, 3, 4])

In [23]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [25]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [37]:
arr1[:,[0,-1]]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [38]:
#EDA
arr

array([1, 2, 3, 5])

In [39]:
arr<2

array([ True, False, False, False])

In [40]:
arr[arr<2]

array([1])

In [41]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [42]:
arr1.shape

(3, 5)

In [44]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [45]:
#mechanism to create an array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [48]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [51]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [52]:
arr *arr

array([ 1,  4,  9, 25])

In [53]:
arr1 *2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [55]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
#generates random num less than 20
np.random.randint(20)

4

In [64]:
np.random.randn(5,6)

array([[-0.04915806, -1.45441011, -0.56323038, -0.12528333,  0.18445796,
        -0.26432999],
       [-1.26487742, -0.5449556 , -0.5738942 ,  1.12212563,  0.26934241,
        -0.63179905],
       [-0.89057504,  1.83069186, -1.21513998,  0.19369756,  0.56871619,
         0.12712572],
       [-0.02137833, -0.88395831, -0.61046542, -0.22611202, -0.0681772 ,
        -1.02285516],
       [-0.02351939, -0.08712561, -0.36838569, -0.49786171,  0.48475299,
        -0.61412575]])

In [65]:
np.random.random_sample((4,7))

array([[0.7620926 , 0.80748763, 0.87175717, 0.72044731, 0.75190475,
        0.10400205, 0.36506187],
       [0.47072631, 0.48057448, 0.35889179, 0.30156301, 0.02529195,
        0.87146514, 0.72886463],
       [0.94740025, 0.06659741, 0.03266636, 0.47994728, 0.38366323,
        0.72351556, 0.19670541],
       [0.70889984, 0.85870066, 0.00991194, 0.26546863, 0.3708851 ,
        0.5850078 , 0.8739392 ]])