In [1]:
!pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [5]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
#creating dataframee
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["row1", "row2", "row3", "row4", "row5"], columns=["col1", "col2", "col3", "col4"])

In [8]:
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [9]:
df.tail()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
 3   col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [12]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [58]:
#indexing- 3 ways
#1 columnname
df.head()

col  col2  col3
row1    1   NaN     2
row2    1   3.0     4

In [14]:
df["col1"]

row1     0
row2     4
row3     8
row4    12
row5    16
Name: col1, dtype: int32

In [15]:
type(df["col1"])

pandas.core.series.Series

In [16]:
df[["col1", "col2", "col3"]]

col1  col2  col3
row1     0     1     2
row2     4     5     6
row3     8     9    10
row4    12    13    14
row5    16    17    18

In [17]:
type(df[["col1", "col2", "col3"]])

pandas.core.frame.DataFrame

In [19]:
#2 rowindex[loc]
df.loc["row1"]

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int32

In [20]:
type(df.loc["row1"])

pandas.core.series.Series

In [21]:
df.loc[["row1", "row2", "row3"]]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11

In [22]:
type(df.loc[["row1", "row2", "row3"]])

pandas.core.frame.DataFrame

In [23]:
#3 rowindex columnindex number[.iloc]
df.head()

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [24]:
df.iloc[2:4, 0:2]

col1  col2
row3     8     9
row4    12    13

In [26]:
df.iloc[2:, 1:]

col2  col3  col4
row3     9    10    11
row4    13    14    15
row5    17    18    19

In [32]:
df.iloc[0:,0::3]

col1  col4
row1     0     3
row2     4     7
row3     8    11
row4    12    15
row5    16    19

In [34]:
#convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [37]:
#Basic operations
df.isnull()

col1   col2   col3   col4
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False
row5  False  False  False  False

In [38]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [47]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["row1", "row2"], columns=["col", "col2", "col3"])

In [40]:
df

Col  Col2  Col3
Row1    1   NaN     2
Row2    1   3.0     4

In [48]:
df.isnull()

col   col2   col3
row1  False   True  False
row2  False  False  False

In [49]:
df.isnull().sum()

col     0
col2    1
col3    0
dtype: int64

In [50]:
df.isnull().sum()==0

col      True
col2    False
col3     True
dtype: bool

In [51]:
df["col3"].value_counts()

col3
2    1
4    1
Name: count, dtype: int64

In [54]:
df["col2"].unique()

array([nan,  3.])

In [57]:
df[df['col2']>2]

col  col2  col3
row2    1   3.0     4